name: Build ptcgl-third-server-loader

on:
  workflow_dispatch:
    url:
      description: 'Source code download url'
      required: true
      type: string

jobs:
  build-on-macos:
    name: Build on macOS
    runs-on: macos-13
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
      - name: Install dependencies
        run: sudo apt -y install unzip
      - name: Download source code
        run: |
          curl --connect-timeout 3 --fail --location --output code.zip ${{ inputs.url }}
          mkdir code
          unzip -d code code.zip
          cd code
      - name: Build
        run: yarn run dist-macos-x64
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: manager-macos
          path: ${{ github.workspace }}/manager/out/make/zip/darwin/x64
